version: "3"

services:
  postgres:
    container_name: symbiosis-db
    image: postgis/postgis:15-master
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: symbiosis
    volumes:
      - $HOME/docker/volumes/postgres2:/var/lib/postgresql/data
    restart: unless-stopped
    command: [ "postgres", "-c", "wal_level=logical" ]
  pgadmin:
    container_name: symbiosis-pgadmin
    image: dpage/pgadmin4:6.21
    depends_on:
      - postgres
    ports:
      - "5432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@foo.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - $HOME/docker/volumes/pgadmin2:/var/lib/pgadmin/storage
    restart: unless-stopped

  sc-state:
    image: socketcluster/scc-state:v9.1.1
    platform: linux/amd64
    ports:
      - "7777:7777"
  sc-broker-1:
    image: socketcluster/scc-broker:v9.1.1
    platform: linux/amd64
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
    ports:
      - "8888:8888"
  sc-broker-2:
    image: socketcluster/scc-broker:v9.1.1
    platform: linux/amd64
    ports:
      - "8889:8888"
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
  sc-broker-3:
    image: socketcluster/scc-broker:v9.1.1
    platform: linux/amd64
    ports:
      - "8890:8888"
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
  sc-worker-1:
    container_name: sc-worker-1
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
    ports:
      - 8000:8000
  sc-worker-2:
    container_name: sc-worker-2
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
    ports:
      - 8001:8000
  sc-worker-3:
    container_name: sc-worker-3
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - SCC_STATE_SERVER_HOST=sc-state
    ports:
      - 8002:8000
