version: "3"

services:
  postgres:
    container_name: symbiosis-db
    image: postgis/postgis:15-master
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: symbiosis
    volumes:
      - $HOME/docker/volumes/postgres2:/var/lib/postgresql/data
    restart: unless-stopped
    command: [ "postgres", "-c", "wal_level=logical" ]
  pgadmin:
    container_name: symbiosis-pgadmin
    image: dpage/pgadmin4:6.21
    depends_on:
      - postgres
    ports:
      - "5432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@foo.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - $HOME/docker/volumes/pgadmin2:/var/lib/pgadmin/storage
    restart: unless-stopped

  # nats comm
  nats:
    container_name: nats
    platform: linux/amd64
    image: nats:2.9.0
    ports:
      - 4223:4222
    command:
      - "--jetstream"
